# Hibernate Dialect for H2 Database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Show SQL statements in the console
spring.jpa.show-sql=true

# Format SQL statements in the console
spring.jpa.properties.hibernate.format_sql=true

# Enable batch processing
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
